require 'minitest/autorun'

TESTS = [

    # 6.1 Escapes
    ['308', %Q{\\!\\"\\#\\$\\%\\&\\'\\(\\)\\*\\+\\,\\-\\.\\/\\:\\;\\<\\=\\>\\?\\@\\[\\\\\\]\\^\\_\\`\\\{\\|\\\}\\~}, %Q{!&quot;#$%&amp;'()*+,-./:;&lt;=&gt;?@[\\]^_`\{|\}~}],
    ['309', %Q{\\→\\A\\a\\ \\3\\φ\\«}, %Q{\\→\\A\\a\\ \\3\\φ\\«}],
    ['310a', %Q{\\*not emphasized*}, %Q{*not emphasized*}],
    ['310b', %Q{\\<br/> not a tag}, %Q{&lt;br/&gt; not a tag}],
    ['310c', %Q{\\[not a link](/foo)}, %Q{[not a link](/foo)}],
    ['310d', %Q{\\`not code`}, %Q{`not code`}],
    ['310e', %Q{1\\. not a list}, %Q{1. not a list}],
    ['310f', %Q{\\* not a list}, %Q{* not a list}],
    ['310g', %Q{\\# not a heading}, %Q{# not a heading}],
    ['310h', %Q{\\[foo]: /url "not a reference"}, %Q{[foo]: /url &quot;not a reference&quot;}],
    ['310i', %Q{\\&ouml; not a character entity}, %Q{&amp;ouml; not a character entity}],
    ['311', %Q{\\*emphasis*}, %Q{\\<em>emphasis</em>}],
    ['312', %Q{foo\\\nbar}, %Q{foo<br />bar}],
    ['313', %Q{ `` \\[\\` ``}, %Q{<code>\\[\\`</code>}],
    ['316', %Q{ <http://example.com?find=\\*>}, %Q{<a href="http://example.com?find=%5C*">http://example.com?find=\\*</a>}],
    ['317', %Q{<a href="/bar\\/)">}, %Q{<a href="/bar\\/)">}],
    ['318', %Q{[foo](/bar\\* "ti\\*tle")}, %Q{<a href="/bar*" title="ti*tle">foo</a>}],

    # 6.2 Entities
    ['325', %Q{&copy}, %Q{&amp;copy</p>}],
    ['326', %Q{&MadeUpEntity;}, %Q{&amp;MadeUpEntity;</p>}],
    ['327', %Q{<a href="&ouml;&ouml;.html">}, %Q{<a href="&ouml;&ouml;.html"></p>}],
    ['328', %Q{[foo](/f&ouml;&ouml; "f&ouml;&ouml;")}, %Q{<a href="/f%C3%B6%C3%B6" title="föö">foo</a></p>}],
    ['329', %Q{[foo]\n\n[foo]: /f&ouml;&ouml; "f&ouml;&ouml;"}, %Q{<a href="/f%C3%B6%C3%B6" title="föö">foo</a></p>}],
    ['330', %Q{``` f&ouml;&ouml;\nfoo\n```<pre><code class="language-föö">foo\n</code></pre>}],
    ['331', %Q{`f&ouml;&ouml;`}, %Q{<code>f&amp;ouml;&amp;ouml;</code></p>}],
    ['333', %Q{&#42;foo&#42;\n*foo*}, %Q{*foo*\n<em>foo</em></p>}],
    ['335', %Q{foo&#10;&#10;bar}, %Q{foo\n\nbar</p>}],
    ['336', %Q{&#9;foo\n}, %Q{→foo</p>}],
    ['337', %Q{[a](url &quot;tit&quot;)\n}, %Q{[a](url &quot;tit&quot;)</p>}],

    # 6.3 Code spans
    ['338', %Q{`foo`}, %Q{<code>foo</code>}],
    ['339', %Q{`` foo ` bar ``}, %Q{<code>foo ` bar</code>}],
    ['340', %Q{` `` `}, %Q{<code>``</code>}],
    ['341', %Q{`  ``  `}, %Q{<code> `` </code>}],
    ['342', %Q{` a`}, %Q{<code> a</code>}],
    ['343', %Q{` b `}, %Q{<code> b </code>}],
    ['344', %Q{` `\n`  `}, %Q{<code> </code>\n<code>  </code>}],
    ['345', %Q{``\nfoo\nbar  \nbaz\n``}, %Q{<code>foo bar   baz</code>}],
    ['346', %Q{``\nfoo \n``}, %Q{<code>foo </code>}],
    ['347', %Q{`foo   bar \nbaz`}, %Q{<code>foo   bar  baz</code>}],
    ['348', %Q{`foo\\`bar`}, %Q{<code>foo\\</code>bar`}],
    ['349', %Q{``foo`bar``}, %Q{<code>foo`bar</code>}],
    ['350', %Q{` foo `` bar `}, %Q{<code>foo `` bar</code>}],
    ['351', %Q{*foo`*`}, %Q{*foo<code>*</code>}],
    ['352', %Q{[not a `link](/foo`)}, %Q{[not a <code>link](/foo</code>)}],
    ['353', %Q{`<a href="`">`}, %Q{<code>&lt;a href=&quot;</code>&quot;&gt;`}],
    ['354', %Q{<a href="`">`}, %Q{<a href="`">`}],
    ['355', %Q{`<http://foo.bar.`baz>`}, %Q{<code>&lt;http://foo.bar.</code>baz&gt;`}],
    ['356', %Q{ <http://foo.bar.`baz>`}, %Q{<a href="http://foo.bar.%60baz">http://foo.bar.`baz</a>`}],
    ['357', %Q{```foo``}, %Q{```foo``}],
    ['358', %Q{`foo}, %Q{`foo}],
    ['359', %Q{`foo``bar``}, %Q{`foo<code>bar</code>}],

    # 6.4 Emphasis and strong emphasis
    ['360', %Q{*foo bar*}, %Q{<em>foo bar</em>}],
    ['361', %Q{a * foo bar*}, %Q{a * foo bar*}],
    ['362', %Q{a*"foo"*}, %Q{a*&quot;foo&quot;*}],
    ['363', %Q{* a *}, %Q{* a *}],
    ['364', %Q{foo*bar*}, %Q{foo<em>bar</em>}],
    ['365', %Q{5*6*78}, %Q{5<em>6</em>78}],
    ['366', %Q{_foo bar_}, %Q{<em>foo bar</em>}],
    ['367', %Q{_ foo bar_}, %Q{_ foo bar_}],
    ['368', %Q{a_"foo"_}, %Q{a_&quot;foo&quot;_}],
    ['369', %Q{foo_bar_}, %Q{foo_bar_}],
    ['370', %Q{5_6_78}, %Q{5_6_78}],
    ['372', %Q{aa_"bb"_cc}, %Q{aa_&quot;bb&quot;_cc}],
    ['373', %Q{foo-_(bar)_}, %Q{foo-<em>(bar)</em>}],
    ['374', %Q{_foo*}, %Q{_foo*}],
    ['375', %Q{*foo bar *}, %Q{*foo bar *}],
    ['376', %Q{*foo bar\n*}, %Q{*foo bar\n*}],
    ['377', %Q{*(*foo)}, %Q{*(*foo)}],
    ['378', %Q{*(*foo*)*}, %Q{<em>(<em>foo</em>)</em>}],
    ['379', %Q{*foo*bar}, %Q{<em>foo</em>bar}],
    ['380', %Q{_foo bar _}, %Q{_foo bar _}],
    ['381', %Q{_(_foo)}, %Q{_(_foo)}],
    ['382', %Q{_(_foo_)_}, %Q{<em>(<em>foo</em>)</em>}],
    ['383', %Q{_foo_bar}, %Q{_foo_bar}],
    ['385', %Q{_foo_bar_baz_}, %Q{<em>foo_bar_baz</em>}],
    ['386', %Q{_(bar)_.}, %Q{<em>(bar)</em>.}],
    ['387', %Q{**foo bar**}, %Q{<strong>foo bar</strong>}],
    ['388', %Q{** foo bar**}, %Q{** foo bar**}],
    ['389', %Q{a**"foo"**}, %Q{a**&quot;foo&quot;**}],
    ['390', %Q{foo**bar**}, %Q{foo<strong>bar</strong>}],
    ['391', %Q{__foo bar__}, %Q{<strong>foo bar</strong>}],
    ['392', %Q{__ foo bar__}, %Q{__ foo bar__}],
    ['393', %Q{__\nfoo bar__}, %Q{__\nfoo bar__}],
    ['394', %Q{a__"foo"__}, %Q{a__&quot;foo&quot;__}],
    ['395', %Q{foo__bar__}, %Q{foo__bar__}],
    ['396', %Q{5__6__78}, %Q{5__6__78}],
    ['398', %Q{__foo, __bar__, baz__}, %Q{<strong>foo, <strong>bar</strong>, baz</strong>}],
    ['399', %Q{foo-__(bar)__}, %Q{foo-<strong>(bar)</strong>}],
    ['400', %Q{**foo bar **}, %Q{**foo bar **}],
    ['401', %Q{**(**foo)}, %Q{**(**foo)}],
    ['402', %Q{*(**foo**)*}, %Q{<em>(<strong>foo</strong>)</em>}],
    ['404', %Q{**foo "*bar*" foo**}, %Q{<strong>foo &quot;<em>bar</em>&quot; foo</strong>}],
    ['405', %Q{**foo**bar}, %Q{<strong>foo</strong>bar}],
    ['406', %Q{__foo bar __}, %Q{__foo bar __}],
    ['407', %Q{__(__foo)}, %Q{__(__foo)}],
    ['408', %Q{_(__foo__)_}, %Q{<em>(<strong>foo</strong>)</em>}],
    ['409', %Q{__foo__bar}, %Q{__foo__bar}],
    ['411', %Q{__foo__bar__baz__}, %Q{<strong>foo__bar__baz</strong>}],
    ['412', %Q{__(bar)__.}, %Q{<strong>(bar)</strong>.}],
    ['413', %Q{*foo [bar](/url)*}, %Q{<em>foo <a href="/url">bar</a></em>}],
    ['414', %Q{*foo\nbar*}, %Q{<em>foo\nbar</em>}],
    ['415', %Q{_foo __bar__ baz_}, %Q{<em>foo <strong>bar</strong> baz</em>}],
    ['416', %Q{_foo _bar_ baz_}, %Q{<em>foo <em>bar</em> baz</em>}],
    ['417', %Q{__foo_ bar_}, %Q{<em><em>foo</em> bar</em>}],
    ['418', %Q{*foo *bar**}, %Q{<em>foo <em>bar</em></em>}],
    ['419', %Q{*foo **bar** baz*}, %Q{<em>foo <strong>bar</strong> baz</em>}],
    ['420', %Q{*foo**bar**baz*}, %Q{<em>foo<strong>bar</strong>baz</em>}],
    ['421', %Q{*foo**bar*}, %Q{<em>foo**bar</em>}],
    ['422', %Q{***foo** bar*}, %Q{<em><strong>foo</strong> bar</em>}],
    ['423', %Q{*foo **bar***}, %Q{<em>foo <strong>bar</strong></em>}],
    ['424', %Q{*foo**bar***}, %Q{<em>foo<strong>bar</strong></em>}],
    ['425', %Q{foo***bar***baz}, %Q{foo<em><strong>bar</strong></em>baz}],
    ['426', %Q{foo******bar*********baz}, %Q{foo<strong><strong><strong>bar</strong></strong></strong>***baz}],
    ['427', %Q{*foo **bar *baz* bim** bop*}, %Q{<em>foo <strong>bar <em>baz</em> bim</strong> bop</em>}],
    ['428', %Q{*foo [*bar*](/url)*}, %Q{<em>foo <a href="/url"><em>bar</em></a></em>}],
    ['429', %Q{** is not an empty emphasis}, %Q{** is not an empty emphasis}],
    #['430', %Q{**** is not an empty strong emphasis}, %Q{**** is not an empty strong emphasis}],
    ['431', %Q{**foo [bar](/url)**}, %Q{<strong>foo <a href="/url">bar</a></strong>}],
    ['432', %Q{**foo\nbar**}, %Q{<strong>foo\nbar</strong>}],
    ['433', %Q{__foo _bar_ baz__}, %Q{<strong>foo <em>bar</em> baz</strong>}],
    ['434', %Q{__foo __bar__ baz__}, %Q{<strong>foo <strong>bar</strong> baz</strong>}],
    ['435', %Q{____foo__ bar__}, %Q{<strong><strong>foo</strong> bar</strong>}],
    ['436', %Q{**foo **bar****}, %Q{<strong>foo <strong>bar</strong></strong>}],
    ['437', %Q{**foo *bar* baz**}, %Q{<strong>foo <em>bar</em> baz</strong>}],
    ['438', %Q{**foo*bar*baz**}, %Q{<strong>foo<em>bar</em>baz</strong>}],
    ['439', %Q{***foo* bar**}, %Q{<strong><em>foo</em> bar</strong>}],
    ['440', %Q{**foo *bar***}, %Q{<strong>foo <em>bar</em></strong>}],
    ['441', %Q{**foo *bar **baz**\nbim* bop**}, %Q{<strong>foo <em>bar <strong>baz</strong>\nbim</em> bop</strong>}],
    ['442', %Q{**foo [*bar*](/url)**}, %Q{<strong>foo <a href="/url"><em>bar</em></a></strong>}],
    ['443', %Q{__ is not an empty emphasis}, %Q{__ is not an empty emphasis}],
    ['444', %Q{____ is not an empty strong emphasis}, %Q{____ is not an empty strong emphasis}],
    ['445', %Q{foo ***}, %Q{foo ***}],
    ['446', %Q{foo *\\**}, %Q{foo <em>*</em>}],
    ['447', %Q{foo *_*}, %Q{foo <em>_</em>}],
    ['448', %Q{foo *****}, %Q{foo *****}],
    ['449', %Q{foo **\\***}, %Q{foo <strong>*</strong>}],
    ['450', %Q{foo **_**}, %Q{foo <strong>_</strong>}],
    ['451', %Q{**foo*}, %Q{*<em>foo</em>}],
    ['452', %Q{*foo**}, %Q{<em>foo</em>*}],
    ['453', %Q{***foo**}, %Q{*<strong>foo</strong>}],
    ['454', %Q{****foo*}, %Q{***<em>foo</em>}],
    ['455', %Q{**foo***}, %Q{<strong>foo</strong>*}],
    ['456', %Q{*foo****}, %Q{<em>foo</em>***}],
    ['457', %Q{foo ___}, %Q{foo ___}],
    ['458', %Q{foo _\\__}, %Q{foo <em>_</em>}],
    ['459', %Q{foo _*_}, %Q{foo <em>*</em>}],
    ['460', %Q{foo _____}, %Q{foo _____}],
    ['461', %Q{foo __\\___}, %Q{foo <strong>_</strong>}],
    ['462', %Q{foo __*__}, %Q{foo <strong>*</strong>}],
    ['463', %Q{__foo_}, %Q{_<em>foo</em>}],
    ['464', %Q{_foo__}, %Q{<em>foo</em>_}],
    ['465', %Q{___foo__}, %Q{_<strong>foo</strong>}],
    ['466', %Q{____foo_}, %Q{___<em>foo</em>}],
    ['467', %Q{__foo___}, %Q{<strong>foo</strong>_}],
    ['468', %Q{_foo____}, %Q{<em>foo</em>___}],
    ['469', %Q{**foo**}, %Q{<strong>foo</strong>}],
    ['470', %Q{*_foo_*}, %Q{<em><em>foo</em></em>}],
    ['471', %Q{__foo__}, %Q{<strong>foo</strong>}],
    ['472', %Q{_*foo*_}, %Q{<em><em>foo</em></em>}],
    ['473', %Q{****foo****}, %Q{<strong><strong>foo</strong></strong>}],
    ['474', %Q{____foo____}, %Q{<strong><strong>foo</strong></strong>}],
    ['475', %Q{******foo******}, %Q{<strong><strong><strong>foo</strong></strong></strong>}],
    ['476', %Q{***foo***}, %Q{<em><strong>foo</strong></em>}],
    ['477', %Q{_____foo_____}, %Q{<em><strong><strong>foo</strong></strong></em>}],
    ['478', %Q{*foo _bar* baz_}, %Q{<em>foo _bar</em> baz_}],
    ['479', %Q{*foo __bar *baz bim__ bam*}, %Q{<em>foo <strong>bar *baz bim</strong> bam</em>}],
    ['480', %Q{**foo **bar baz**}, %Q{**foo <strong>bar baz</strong>}],
    ['481', %Q{*foo *bar baz*}, %Q{*foo <em>bar baz</em>}],
    ['482', %Q{*[bar*](/url)}, %Q{*<a href="/url">bar*</a>}],
    ['483', %Q{_foo [bar_](/url)}, %Q{_foo <a href="/url">bar_</a>}],
    #['484', %Q{*<img src="foo" title="*"/>}, %Q{*<img src="foo" title="*"/>}],
    #['485', %Q{**<a href="**">}, %Q{**<a href="**">}],
    #['486', %Q{__<a href="__">}, %Q{__<a href="__">}],
    ['487', %Q{*a `*`*}, %Q{<em>a <code>*</code></em>}],
    ['488', %Q{_a `_`_}, %Q{<em>a <code>_</code></em>}],
    #['489', %Q{**a<http://foo.bar/?q=**>}, %Q{**a<a href="http://foo.bar/?q=**">http://foo.bar/?q=**</a>}],
    #['490', %Q{__a<http://foo.bar/?q=__>}, %Q{__a<a href="http://foo.bar/?q=__">http://foo.bar/?q=__</a>}],

    # 6.5 Strikethrough
    ['491', %Q{~~Hi~~ Hello, world!}, %Q{<p><del>Hi</del> Hello, world!</p>}],
    ['492', %Q{This ~~has a\n\nnew paragraph~~}, %Q{This ~~has a\n\nnew paragraph~~}],

    # 6.6 Links
    # Normal
    ['493', %Q{[link](/uri "title")}, %Q{<a href="/uri" title="title">link</a>}],
    ['494', %Q{[link](/uri)}, %Q{<a href="/uri">link</a>}],
    ['495', %Q{[link]()}, %Q{<a href="">link</a>}],
    ['496', %Q{[link](<>)}, %Q{<a href="">link</a>}],
    ['497', %Q{[link](/my uri)}, %Q{[link](/my uri)}],
    ['498', %Q{[link](</my uri>)}, %Q{<a href="/my%20uri">link</a>}],
    ['499', %Q{[link](foo\nbar)}, %Q{[link](foo\nbar)}],
    ['500', %Q{[link](<foo\nbar>)}, %Q{[link](<foo\nbar>)}],
    ['501', %Q{[a](<b)c>)}, %Q{<a href="b)c">a</a>}],
    ['502', %Q{[link](<foo\\>)}, %Q{[link](&lt;foo&gt;)}],
    ['503', %Q{[a](<b)c\n[a](<b)c>\n[a](<b>c)}, %Q{[a](&lt;b)c\n[a](&lt;b)c&gt;\n[a](<b>c)}],
    ['504', %Q{[link](\\(foo\\))}, %Q{<a href="(foo)">link</a>}],
    ['505', %Q{[link](foo(and(bar)))}, %Q{<a href="foo(and(bar))">link</a>}],
    ['506', %Q{[link](foo\\(and\\(bar\\))}, %Q{<a href="foo(and(bar)">link</a>}],
    ['507', %Q{[link](<foo(and(bar)>)}, %Q{<a href="foo(and(bar)">link</a>}],
    ['508', %Q{[link](foo\\)\\:)}, %Q{<a href="foo):">link</a>}],
    ['509', %Q{[link](#fragment)[link](http://example.com#fragm}],
    ['510', %Q{[link](foo\bar)}, %Q{<a href="foo%5Cbar">link</a>}],
    ['512', %Q{[link]("title")}, %Q{<a href="%22title%22">link</a>}],
    ['513a', %Q{[link](/url "title")}, %Q{<a href="/url" title="title">link}],
    ['513b', %Q{[link](/url 'title')}, %Q{<a href="/url" title="title">link}],
    ['513c', %Q{[link](/url (title))}, %Q{<a href="/url" title="title">link</a>}],
    ['514', %Q{[link](/url "title "&quot;")}, %Q{<a href="/url" title="title &quot;&quot;">link</a>}],
    ['515', %Q{[link](/url "title")}, %Q{<a href="/url%C2%A0%22title%22">link</a>}],
    ['516', %Q{[link](/url "title "and" title")}, %Q{[link](/url &quot;title &quot;and&quot; title&quot;)}],
    ['517', %Q{[link](/url 'title "and" title')}, %Q{<a href="/url" title="title &quot;and&quot; title">link</a>}],
    ['518', %Q{[link](   /uri\n  "title"  )}, %Q{<a href="/uri" title="title">link</a>}],
    ['519', %Q{[link] (/uri)}, %Q{[link] (/uri)}],
    ['520', %Q{[link [foo [bar]]](/uri)}, %Q{<a href="/uri">link [foo [bar]]</a>}],
    ['521', %Q{[link] bar](/uri)}, %Q{[link] bar](/uri)}],
    ['522', %Q{[link [bar](/uri)}, %Q{[link <a href="/uri">bar</a>}],
    ['523', %Q{[link \\[bar](/uri)}, %Q{<a href="/uri">link [bar</a>}],
    ['524', %Q{[link *foo **bar** `#`*](/uri)}, %Q{<a href="/uri">link <em>foo <strong>bar</strong> <code>#</code></em></a>}],
    ['525', %Q{[![moon](moon.jpg)](/uri)}, %Q{<a href="/uri"><img src="moon.jpg" alt="moon" /></a>}],
    ['526', %Q{[foo [bar](/uri)](/uri)}, %Q{[foo <a href="/uri">bar</a>](/uri)}],
    ['527', %Q{[foo *[bar [baz](/uri)](/uri)*](/uri)}, %Q{[foo <em>[bar <a href="/uri">baz</a>](/uri)</em>](/uri)}],
    ['528', %Q{![[[foo](uri1)](uri2)](uri3)}, %Q{<img src="uri3" alt="[foo](uri2)" />}],
    ['529', %Q{*[foo*](/uri)}, %Q{*<a href="/uri">foo*</a>}],
    ['530', %Q{[foo *bar](baz*)}, %Q{<a href="baz*">foo *bar</a>}],
    ['531', %Q{*foo [bar* baz]}, %Q{<em>foo [bar</em> baz]}],
    ['532', %Q{[foo <bar attr="](baz)">}, %Q{[foo <bar attr="](baz)">}],
    ['533', %Q{[foo`](/uri)`}, %Q{[foo<code>](/uri)</code>}],
    ['534', %Q{[foo<http://example.com/?search=](uri)>}, %Q{[foo<a href="http://example.com/?search=%5D(uri)">http://example.com/?search=](uri)</a>}],

    # Reference Style
    ['535', %Q{[foo][bar]\n\n[bar]: /url "title"}, %Q{<a href="/url" title="title">foo</a>}],
    ['536', %Q{[link [foo [bar]]][ref]\n\n[ref]: /uri}, %Q{<a href="/uri">link [foo [bar]]</a>}],
    ['537', %Q{[link \\[bar][ref]\n\n[ref]: /uri}, %Q{<a href="/uri">link [bar</a>}],
    ['538', %Q{[link *foo **bar** `#`*][ref]\n\n[ref]: /uri}, %Q{<a href="/uri">link <em>foo <strong>bar</strong> <code>#</code></em></a>}],
    ['539', %Q{[![moon](moon.jpg)][ref]\n\n[ref]: /uri}, %Q{<a href="/uri"><img src="moon.jpg" alt="moon" /></a>}],
    ['540', %Q{[foo [bar](/uri)][ref]\n\n[ref]: /uri}, %Q{[foo <a href="/uri">bar</a>]<a href="/uri">ref</a>}],
    ['541', %Q{[foo *bar [baz][ref]*][ref]\n\n[ref]: /uri}, %Q{[foo <em>bar <a href="/uri">baz</a></em>]<a href="/uri">ref</a>}],
    ['542', %Q{*[foo*][ref]\n\n[ref]: /uri}, %Q{*<a href="/uri">foo*</a>}],
    ['543', %Q{[foo *bar][ref]*\n\n[ref]: /uri}, %Q{<a href="/uri">foo *bar</a>*}],
    ['544', %Q{[foo <bar attr="][ref]">\n\n[ref]: /uri}, %Q{[foo <bar attr="][ref]">}],
    ['545', %Q{[foo`][ref]`\n\n[ref]: /uri}, %Q{[foo<code>][ref]</code>}],
    ['546', %Q{[foo<http://example.com/?search=][ref]>\n\n[ref]: /uri}, %Q{[foo<a href="http://example.com/?search=%5D%5Bref%5D">http://example.com/?search=][ref]</a>}],
    ['547', %Q{[foo][BaR]\n\n[bar]: /url "title"}, %Q{<a href="/url" title="title">foo</a>}],
    ['548', %Q{[ẞ]\n\n[SS]: /url}, %Q{<a href="/url">ẞ</a>}],
    ['549', %Q{[Foo\n bar]: /url\n\n[Baz][Foo bar]}, %Q{<a href="/url">Baz</a>}],
    ['550', %Q{[foo] [bar]\n\n[bar]: /url "title"}, %Q{[foo] <a href="/url" title="title">bar</a>}],
    ['551', %Q{[foo]\n[bar]\n\n[bar]: /url "title"}, %Q{[foo]\n<a href="/url" title="title">bar</a>}],
    ['552', %Q{[foo]: /url1\n\n[foo]: /url2\n\n[bar][foo]}, %Q{<a href="/url1">bar</a>}],
    ['553', %Q{[bar][foo\\!]\n\n[foo!]: /url}, %Q{[bar][foo!]}],
    ['554', %Q{[foo][ref[]\n\n[ref[]: /uri}, %Q{[foo][ref[]\n[ref[]: /uri}],
    ['555', %Q{[foo][ref[bar]]\n\n[ref[bar]]: /uri}, %Q{[foo][ref[bar]]\n[ref[bar]]: /uri}],
    ['556', %Q{[[[foo]]]\n\n[[[foo]]]: /url}, %Q{[[[foo]]]\n[[[foo]]]: /url}],
    ['557', %Q{[foo][ref\\[]\n\n[ref\\[]: /uri}, %Q{<a href="/uri">foo</a>}],
    ['558', %Q{[bar\\]: /uri\n\n[bar\\]}, %Q{<a href="/uri">bar\\</a>}],
    ['559', %Q{[]\n\n[]: /uri}, %Q{[]\n[]: /uri}],
    ['560', %Q{[\n ]\n\n[\n ]: /uri}, %Q{[\n]\n[\n]: /uri}],
    ['561', %Q{[foo][]\n\n[foo]: /url "title"}, %Q{<a href="/url" title="title">foo</a>}],
    ['562', %Q{[*foo* bar][]\n\n[*foo* bar]: /url "title"}, %Q{<a href="/url" title="title"><em>foo</em> bar</a>}],
    ['563', %Q{[Foo][]\n\n[foo]: /url "title"}, %Q{<a href="/url" title="title">Foo</a>}],
    ['564', %Q{[foo] \n[]\n\n[foo]: /url "title"}, %Q{<a href="/url" title="title">foo</a>\n[]}],
    ['565', %Q{[foo]\n\n[foo]: /url "title"}, %Q{<a href="/url" title="title">foo</a>}],
    ['566', %Q{[*foo* bar]\n\n[*foo* bar]: /url "title"}, %Q{<a href="/url" title="title"><em>foo</em> bar</a>}],
    ['567', %Q{[[*foo* bar]]\n\n[*foo* bar]: /url "title"}, %Q{[<a href="/url" title="title"><em>foo</em> bar</a>]}],
    ['568', %Q{[[bar [foo]\n\n[foo]: /url}, %Q{[[bar <a href="/url">foo</a>}],
    ['569', %Q{[Foo]\n\n[foo]: /url "title"}, %Q{<a href="/url" title="title">Foo</a>}],
    ['570', %Q{[foo] bar\n\n[foo]: /url}, %Q{<a href="/url">foo</a> bar}],
    ['571', %Q{\\[foo]\n\n[foo]: /url "title"}, %Q{[foo]}],
    ['572', %Q{[foo*]: /url\n\n*[foo*]}, %Q{*<a href="/url">foo*</a>}],
    ['573', %Q{[foo][bar]\n\n[foo]: /url1\n[bar]: /url2}, %Q{<a href="/url2">foo</a>}],
    ['574', %Q{[foo][]\n\n[foo]: /url1}, %Q{<a href="/url1">foo</a>}],
    ['575', %Q{[foo]()\n\n[foo]: /url1}, %Q{<a href="">foo</a>}],
    ['576', %Q{[foo](not a link)\n\n[foo]: /url1}, %Q{<a href="/url1">foo</a>(not a link)}],
    ['577', %Q{[foo][bar][baz]\n\n[baz]: /url}, %Q{[foo]<a href="/url">bar</a>}],
    ['578', %Q{[foo][bar][baz]\n\n[baz]: /url1\n[bar]: /url2}, %Q{<a href="/url2">foo</a><a href="/url1">baz</a>}],
    ['579', %Q{[foo][bar][baz]\n\n[baz]: /url1\n[foo]: /url2}, %Q{[foo]<a href="/url1">bar</a>}],

    # 6.7 Images
    # Normal
    ['580', %Q{![foo](/url "title")}, %Q{<img src="/url" alt="foo" title="title" />}],
    ['582', %Q{![foo ![bar](/url)](/url2)}, %Q{<img src="/url2" alt="foo bar" />}],
    ['583', %Q{![foo [bar](/url)](/url2)}, %Q{<img src="/url2" alt="foo bar" />}],
    ['585', %Q{![foo *bar*][foobar]\n\n[FOOBAR]: train.jpg "train & tracks"}, %Q{<img src="train.jpg" alt="foo bar" title="train &amp; tracks" />}],
    ['586', %Q{![foo](train.jpg)}, %Q{<img src="train.jpg" alt="foo" />}],
    ['587', %Q{My ![foo bar](/path/to/train.jpg  "title"   )}, %Q{My <img src="/path/to/train.jpg" alt="foo bar" title="title" />}],
    ['588', %Q{![foo](<url>)}, %Q{<img src="url" alt="foo" />}],
    ['589', %Q{![](/url)}, %Q{<img src="/url" alt="" />}],

    # Reference Style
    ['581', %Q{![foo *bar*]\n\n[foo *bar*]: train.jpg "train & tracks"}, %Q{<img src="train.jpg" alt="foo bar" title="train &amp; tracks" />}],
    ['584', %Q{![foo *bar*][]\n\n[foo *bar*]: train.jpg "train & tracks"}, %Q{<img src="train.jpg" alt="foo bar" title="train &amp; tracks" />}],
    ['590', %Q{![foo][bar]\n\n[bar]: /url}, %Q{<img src="/url" alt="foo" />}],
    ['591', %Q{![foo][bar]\n\n[BAR]: /url}, %Q{<img src="/url" alt="foo" />}],
    ['592', %Q{![foo][]\n\n[foo]: /url "title"}, %Q{<img src="/url" alt="foo" title="title" />}],
    ['593', %Q{![*foo* bar][]\n\n[*foo* bar]: /url "title"}, %Q{<img src="/url" alt="foo bar" title="title" />}],
    ['594', %Q{![Foo][]\n\n[foo]: /url "title"}, %Q{<img src="/url" alt="Foo" title="title" />}],
    ['595', %Q{![foo] \n[]\n\n[foo]: /url "title"}, %Q{<img src="/url" alt="foo" title="title" />\n[]}],
    ['596', %Q{![foo]\n\n[foo]: /url "title"}, %Q{<img src="/url" alt="foo" title="title" />}],
    ['597', %Q{![*foo* bar]\n\n[*foo* bar]: /url "title"}, %Q{<img src="/url" alt="foo bar" title="title" />}],
    ['598', %Q{![[foo]]\n\n[[foo]]: /url "title"}, %Q{![[foo]]]\n[[foo]]: /url &quot;title&quot;}],
    ['599', %Q{![Foo]\n\n[foo]: /url "title"}, %Q{<img src="/url" alt="Foo" title="title" />}],
    ['600', %Q{!\\[foo]\n\n[foo]: /url "title"}, %Q{![foo]}],
    ['601', %Q{\\![foo]\n\n[foo]: /url "title"}, %Q{!<a href="/url" title="title">foo</a>}],

    # Own Testcases
    ['O01', %Q{*[link](/url)*}, %Q{<em><a href="/url">link</a></em>}],
    ['O02', %Q{**[link](/url)**}, %Q{<strong><a href="/url">link</a></strong>}],
    ['O02', %Q{`**[link](/url)**`}, %Q{<code>**[link](/url)**</code>}],
]


class RendererTest < Minitest::Test

  def self.setup
    TESTS.each_with_index do |entry, i|
      name = "test_html_#{i}".to_sym
      define_method name do
        message, input, output = *entry
        parser = MarkdownLineParser.new(input)
        parser.create_markdown_line
        rendered = HtmlRenderer.new(parser.markdown_line).html_string
        assert_equal(output, rendered, "GFM Example #{message}: '#{input}'")
      end
    end

    #TESTS.each_with_index do |entry, i|
    #  name = "test_markdown_#{i}".to_sym
    #  define_method name do
    #    message, input, output = *entry
    #    parser = MarkdownLineParser.new(input)
    #    parser.create_markdown_line
    #    rendered = MarkdownRenderer.new(parser.markdown_line).markdown_string
    #    assert_equal(output, rendered, "GFM Example #{message}: '#{input}'")
    #  end
    #end
  end

  setup

end
